import { drizzle } from 'drizzle-orm/sqlite-proxy';
import { sql } from 'drizzle-orm';
import { querySql, execSql } from './sqlite';
import * as schema from './schema';
import { getMigrations } from '../../drizzle/migrations';

export type DrizzleDb = ReturnType<typeof createDrizzleDb>;

export function createDrizzleDb() {
  return drizzle(
    async (sqlStr, params, method) => {
      try {
        const bindParams = params as unknown[];

        if (method === 'run') {
          await execSql(sqlStr, bindParams);
          return { rows: [] };
        }

        const results = await querySql(sqlStr, bindParams);
        return { rows: results.map((row) => Object.values(row as object)) };
      } catch (e) {
        console.error('Drizzle SQL error:', e);
        throw e;
      }
    },
    { schema }
  );
}

const MIGRATIONS_TABLE = '__drizzle_migrations';
let migrationsRan = false;

/**
 * Run migrations using Drizzle's bundled migration system.
 * Migrations are generated by `drizzle-kit generate` and bundled at build time.
 */
export async function runMigrations(): Promise<void> {
  // Prevent double execution in React StrictMode
  if (migrationsRan) return;
  migrationsRan = true;

  const db = createDrizzleDb();
  const migrations = getMigrations();

  // Create migrations tracking table
  await db.run(sql`
    CREATE TABLE IF NOT EXISTS ${sql.identifier(MIGRATIONS_TABLE)} (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL,
      created_at INTEGER
    )
  `);

  // Get the last applied migration
  const appliedMigrations = await db.all<{ id: number; hash: string; created_at: number }>(
    sql`SELECT id, hash, created_at FROM ${sql.identifier(MIGRATIONS_TABLE)} ORDER BY created_at DESC LIMIT 1`
  );
  const lastApplied = appliedMigrations[0];

  // Filter to only pending migrations
  const pendingMigrations = migrations.filter(
    (m) => !lastApplied || lastApplied.created_at < m.folderMillis
  );

  if (pendingMigrations.length === 0) {
    console.log('No pending migrations');
    return;
  }

  console.log(`Running ${pendingMigrations.length} migration(s)...`);

  // Apply each pending migration
  for (const migration of pendingMigrations) {
    console.log(`Applying migration: ${migration.hash}`);

    for (const statement of migration.sql) {
      await execSql(statement);
    }

    // Record the migration
    await execSql(
      `INSERT INTO "${MIGRATIONS_TABLE}" (hash, created_at) VALUES (?, ?)`,
      [migration.hash, migration.folderMillis]
    );
  }

  // Seed with default document if none exists
  await seedDefaultDocument(db);

  console.log('Migrations complete');
}

async function seedDefaultDocument(db: DrizzleDb): Promise<void> {
  const docs = await db.all<{ id: number }>(sql`SELECT id FROM documents LIMIT 1`);

  if (docs.length === 0) {
    const now = Date.now();
    await execSql(
      'INSERT INTO documents (title, content_json, created_at, updated_at) VALUES (?, ?, ?, ?)',
      ['My Article', JSON.stringify(getDefaultDocumentContent()), now, now]
    );
  }
}

function getDefaultDocumentContent() {
  return {
    type: 'doc',
    content: [
      {
        type: 'heading',
        attrs: { level: 1 },
        content: [{ type: 'text', text: 'Welcome to Vocab Article' }],
      },
      {
        type: 'paragraph',
        content: [
          {
            type: 'text',
            text: 'Start writing or paste your article here. Select any word and mark it as a vocabulary term to track it.',
          },
        ],
      },
      {
        type: 'paragraph',
        content: [
          {
            type: 'text',
            text: 'Highlighted words will show their definitions when you hover over them. You can also add your own notes and custom definitions.',
          },
        ],
      },
    ],
  };
}
