// Auto-bundled migrations for browser SQLite
// This file is auto-generated by drizzle-kit and should be committed to version control.
// To regenerate: run `bun run db:generate` after schema changes

import journal from './meta/_journal.json';
import m0000 from './0000_quick_purifiers.sql?raw';
import m0001 from './0001_exotic_may_parker.sql?raw';

// Migration SQL files in order
const migrationSql: Record<string, string> = {
  '0000_quick_purifiers': m0000,
  '0001_exotic_may_parker': m0001,
};

export interface Migration {
  sql: string[];
  folderMillis: number;
  hash: string;
}

export function getMigrations(): Migration[] {
  return journal.entries.map((entry) => {
    const sql = migrationSql[entry.tag];
    if (!sql) {
      throw new Error(`Migration SQL not found for ${entry.tag}. Please run db:generate.`);
    }
    // Split by statement breakpoint and filter empty statements
    const statements = sql
      .split('--> statement-breakpoint')
      .map((s) => s.trim())
      .filter(Boolean);

    return {
      sql: statements,
      folderMillis: entry.when,
      hash: entry.tag,
    };
  });
}

